name: Deploy Java App to AWS ASG
'on':
  workflow_dispatch: null
  push:
    branches:
      - main
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
      - name: Install Maven 3.3
        run: |
          sudo yum update -y
          sudo yum update -y
          sudo yum install maven -y
          mvn -version
      - name: Build Java Application
        run: |
          mvn clean package
          pwd
      - name: Cache Maven Dependencies
        id: maven-cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: Maven-Cache-self-hosted
          restore-keys: Maven-Cache-self-hosted
          
      - name: aws cred
        uses: aws-actions/configure-aws-credentials@v3
        with:
             aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
             aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
             aws-region: '${{ secrets.AWS_REGION }}'
             
  Docker-Build-Push:
    runs-on: self-hosted  
    steps: 
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Login to Amazon ECR
       run: |
            echo $(aws ecr get-login-password --region $AWS_REGION) | docker login --username AWS --password-stdin $ECR_REGISTRY
     - name: Build Docker Image
       run: |
            sudo docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            sudo docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
