name: Deploy Java App to AWS ASG

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17' # Adjust based on your application's requirements

    - name: Build Java Application
      run: |
        mvn clean package
        pwd

  
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload artifact to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws s3 cp target/*.jar s3://test-soham-bucket/

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        # SSH into EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i soham-alm.pem ubuntu@34.225.254.177 << 'EOF'
        # sudo yum install java-17-openjdk -y # Ensure Java is installed
        # sudo apt install openjdk-17-jre-headless
        aws s3 cp s3://test-soham-bucket/ /home/ubuntu/deploy
        java -jar /home/ubuntu/deploy/*.jar 
        wait 20
        echo "Deploy Application" &
        EOF
